### ISSUE TITLE
Indirect control

### ISSUE THREAD

**Issue by Onixarts** [drmibell/node-red-contrib-simple-gate#2]
Hi,
It would be nice if we could control the gate node without connecting 'wires' to the input. In my case, I want to use multiple gates on a flow, all of them will be controlled by the same trigger. I think instead messing up with multiple wires, the gate node could be controlled by flow/global variable. 
Then I can simply switch variable in one function node (or maybe dedicated control node) to open each gate that "listen" the same variable.
What do You think?

**Comment by drmibell** [comment]
A few thoughts:
This is a valid use case but not a new idea, of course. The earliest proposals I could find for gating used flow/global variables. (See the discussion at https://discourse.nodered.org/t/gate-node-using-blockly/2830.) You might be able to use the flow that I posted there. The `node-red-contrib-message-gate` node might also work for you. In my own projects, I usually distribute control messages to multiple gates using `link` nodes, but I have never tried to control more than a few (three or four) gates from the same source. I can see where things could get messy.

The down side of using variables is that they not as visible as wires. This is less of a problem now that the editor sidebar has a Context Data tab, but it is still not easy to see which nodes read or write these variables. With control messages you can use `debug` nodes when developing or modifying flows.

There is also a minor technical issue. One of the core nodes controlled by a variable will not know the value of that variable until it receives an incoming message and reads the variable. So any status that it displays will not be current until the next message comes in. This does not affect performance, but it can be disconcerting to see no change when the command is sent but a sudden change when a message is received. The author of the `node-red-contrib-message-gate` seems to have found a way around this, but the code is not available on GitHub, so I can only guess how it was done.

If you cannot solve your problem with one of my suggestions and there is enough interest in the community, I would be glad to work on a node that uses variables instead of messages. As a practical matter, I think it would be better to develop a new node and then see whether it could be merged with the existing one.

**Comment by drmibell** [comment]
Update: following the link from npm, I found the source code for `node-red-contrib-message-gate` on GitLab, not GitHub. I have an idea of how the gate keeps its status current, but it uses nodejs tricks that I would have to study before trying.

**Comment by drmibell** [comment]
I have uploaded a new repository to GitHub, [node-red-contrib-remote-gate](https://github.com/drmibell/node-red-contrib-remote-gate), which should meet your requirement. If you can download it from there and try it out, I will be grateful. I would rather not publish it on npm until I have discussed it on the Node-RED forum.

**Comment by Onixarts** [comment]
@drmibell as far I have tested it, works well and do the job :)

**Comment by drmibell** [comment]
Thanks for the feedback. As you will see in the `README`, both the `rc-gate` and `gate-ctl` nodes will display their `Topic` if  no `Name` has been assigned in the Edit dialog. I think this is basically what you want. The icons were selected so that `rc-gate` looks like the ordinary `gate` node, and `gate-ctl` looks like the `link` node, but I am open to suggestions for improvement.
