### ISSUE TITLE
State doesn't persist reboot

### ISSUE THREAD

**Issue by Paul-Reed** [drmibell/node-red-contrib-simple-gate#3]
The node doesn't appear to persist reboot's.

It would be a great improvement if the current state was saved to flow context, so that the same state was retrieved after a reboot.

**Comment by drmibell** [comment]
I will have to think about this (again). The node was developed before persistence was available, so it made sense for the gate to go to its default state on a reboot. When persistent context was introduced, I thought briefly about how (or whether) to implement it, and decided not to use it. My thinking was that users would define the defaults as a fail-safe, so that after a restart the system would start from a known state. In particular, if the user forces a restart because a flow is stuck in a loop, I thought that restoring its state might not be a good idea. Worse yet, the context is saved at intervals that might be too long to cope with changes in some systems. (I think the default is 30 seconds, although it may be adjustable.)  

All that aside, it might be possible to provide an option to restore from saved context if you think it would add real value and there would be demand for it. (Should I put the question to the discussion group?) I will take a look at the code to see how much work it would take.

**Comment by Paul-Reed** [comment]
My user case was in connection with a security lighting controller flow. Previously I've used a switch node https://flows.nodered.org/flow/7c67709fecce1ad5992b695028e57646 but I thought that I'd use your node as it seemed a neater way. However, the lighting flow was enabled and working fine, until I updated some nodes, and had to stop/start node-RED. Unknown to me, the flow was then disabled instead of re-enabled, and my security lighting system was sadly left disabled for the remainder of the night.
If the option you spoke about involved adding additional nodes to save/retrieve flow context, then I would not be gaining anything, and would possibly then revert back to my original solution.

It would be good to have the discussion in the NR forum, if you kick it off, I'll explain my user case.

**Comment by drmibell** [comment]
Thanks for the clarification. I think your use case is something I should address, regardless of any other comments. 

When you have more than one system state that can exist for long periods of time (e.g., day/night, home/away, armed/disarmed, etc.) only one of those states can be the default, but you should be able to have gates return to their current settings after a reboot. I have looked at the code, and it seems relatively easy to give the user an option (checkbox) in the edit dialog to do that instead of starting up in the default state. (I hope it is not important to distinguish between an editor re-deploy, NR restart, and system reboot, because I doubt it's possible.) Obviously, I will have to modify both the .js and .html files and do some testing, so it may take a bit of time. 

In the meanwhile, I would appreciate it if you could continue to use the node, since your input has been really helpful. I will let you know as soon as a revision is available for testing.

**Comment by Paul-Reed** [comment]
Great news! I look forward to this feature being added, but no rush. For now, I just need to remember to manually enable or disable flows after a reboot, NR start or editor re-deploy.

**Comment by drmibell** [comment]
This is how I propose to address the issue. It’s not fully implemented yet, but I wanted to give you a chance to comment.

When the node starts up, it checks to see whether the user wants persistence. If not, it enters the `defaultState`. If so, it tries to retrieve and use its saved state from the context storage. If it fails, it enters the `defaultState`.

The value of having a user option (checkbox) is that some instances of the node could use the default while others use persistence. Any thoughts?

**Comment by Paul-Reed** [comment]
That sounds great, and should accommodate all users (I assume doing it that way will ensure backwards compatibility)

**Comment by Paul-Reed** [comment]
Not working for me, sorry.

After setting 'Restore from saved state' (and setting the state to disable), a NR stop/start results with this -
![persist](https://user-images.githubusercontent.com/973580/49768033-bc764780-fcd2-11e8-821b-c97acd611aa2.gif)

My context storage is set as;

`contextStorage: {
   default: {
       module: "localfilesystem",
       config: {
               flushInterval: 300
               }
   },
   memoryOnly: {
       module: "memory"
   }
},
`

Could the 'default State' dropdown, have 3 states;

- open
- closed
- restore

It seems a contradiction to have `Default State = open` as well as ticking the box `Restore from saved state` when the saved state may be closed.

**Comment by drmibell** [comment]
I'll try to reproduce your problem. If I understand, the status shows the state restored correctly, but the actual state of the gate is not what the status shows. Is that right? 
Two questions:
- what was the default for that gate?
- can you get an inverse case: the status shows `open` but the gate is actually `closed`?

The `Default State` really has to be either open or closed. If the user drags the node from the palette, sets the dropdown to `restore`,  and deploys the node, what state should it be in?

There is no real contradiction. The `Default State` is where the gate goes when first deployed, when it gets a control message with a `default` command, or when it tries and fails to restore its state from saved context. Ticking the box really means "don't use the default unless you have to."

**Comment by drmibell** [comment]
I can't reproduce it. Are you sure about `flushInterval: 300`?  I think the interval is in seconds, so it's possible that the state was not written out to disk before you stopped NR. I know NR is supposed to write it out when it stops, but I suspect something is a bit off. I am working on something to let me look at the storage file and the flow editor at the same time.

**Comment by Paul-Reed** [comment]
> I know NR is supposed to write it out when it stops, but I suspect something is a bit off.

Yes you are correct, there is a problem with node-RED core, as context is not being saved when node-RED is shutdown & restarted using the prescribed commands. i.e. `node-red-stop` & `node-red-start`.
The issue is relevant to not only to this node, but to other nodes which save/restore context.

Leaving the state for >300 seconds, so that it's saved, does restore correctly and survives node-RED stop/starts, as well as reboots. So yes Michael, your node is now working fine here.
Thank you

Paul

**Comment by Paul-Reed** [comment]
I've raised this in the forum - https://discourse.nodered.org/t/persistent-data-not-being-saved/5680

**Comment by drmibell** [comment]
Thanks for posting to the forum. I don't follow the Slack, so I did not know whether the bug was known. Also pleased to hear that the `gate` node is working.

I am glad you raised the issue of persistence and appreciate your help in testing. I will merge the `persistence` branch into the master and release a new version shortly.
