### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by eschava** [drmibell/node-red-contrib-simple-gate#5]
The message like below I get in logs every minute (I think when a message from sensor is received)

29 Dec 10:05:54 - [error] [gate:c1a75881.315b98] TypeError: Cannot read property 'toLowerCase' of undefined

**Comment by drmibell** [comment]
Please post your flow or something similar that gives the error so that I can reproduce it. Thanks.

**Comment by drmibell** [comment]
My best guess is that you are passing a message to the `gate` node with `msg.topic` set to the `Control Topic` and `msg.payload` undefined. Please check and see whether this is the case. In any event, this error produces the message you are seeing, so I will revise the code to give a more informative message.

**Comment by drmibell** [comment]
I have pushed a new version (0.2.1) to npm. It should give the message 'Command must be a string' instead of 'TypeError'. Please let me know whether you continue to get the "TypeError: Cannot read property 'toLowerCase' of undefined" message. Without a copy of your flow, or at least the messages you are passing to the `gate` node, I cannot help you find the underlying source of the problem.

**Comment by eschava** [comment]
Thanks, will update and check

**Comment by eschava** [comment]
Gotcha!
`3 Jan 11:40:36 - [error] [gate:c1a75881.315b98] Command must be a string`
Thanks a lot!
