### ISSUE TITLE
Feature request - option to queue latest message and release on opening the gate

### ISSUE THREAD

**Issue by colinl** [drmibell/node-red-contrib-simple-gate#6]
It would be useful to be able to set the queue size to 1 but have it so that it is the latest message that is saved rather than the oldest.  The result would be that the gate could be used to stop a stream of messages, possibly containing values of a slider for example, then when the gate is opened the latest value is released.

**Comment by colinl** [comment]
Sorry, I have made this feature request on the wrong node, I meant it to be on node-red-contrib-queue-gate. However it now occurs to me that perhaps it would be better as a feature on simple-gate, being a checkbox that says that when gate is closed the latest message can be saved and then released when the gate is opened.

**Comment by drmibell** [comment]
Thanks for the suggestion. In designing the `q-gate` node, I thought about what should happen when the queue is full. The choice I made was to drop any incoming messages until space becomes available. The alternative, keeping only the newest messages, also has advantages. It is simple to code, but I decided not to offer it as an option until there was demand for it. Since you made the request (and it seems that at least one poster on the NR forum could use it), I will make the change and upload the new version as soon as I can test it.

I am reluctant to add this feature to the simple-gate. It can be implemented very easily in the queue-gate without altering its basic functionality, but the simple-gate would lose some of its simplicity with the change.

**Comment by drmibell** [comment]
I just pushed a new version of `node-red-contrib-queue-gate` (1.1.0) that gives the option of queueing the newest, rather than the oldest messages when the queue is full. I've also added an example that should work for the problem posed on the NR forum. It retains the most recent message and releases it on command. I have not uploaded this to npm as yet, so if you have time for testing I would appreciate it. Once the two gate nodes are up to date, the README files will cross-reference each other -- something I had expected (dreaded?) as soon as it was clear that there would be two separate nodes.

**Comment by drmibell** [comment]
Closing, since updates to the documentation have been pushed to npm for node-red-contrib-simple-gate (version 0.2.3) and node-red-contrib-queue-gate (version 1.1.1). The changes are cosmetic, so they will mainly benefit new users. There is no necessity for current users to upgrade.
